name: Deploy to server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Pull
      run: |
        cd /opt/wmgcat.net/repositories
        git clone https://github.com/wmgcat-net/backend
        cd backend
    - name: Run tests
      run: |
        npm install
        npm run test
    - name: Build & Docker
      run: |
        npm run docker:public
    - name: Clear
      run: |
        cd /opt/wmgcat.net/repositories
        rm -rf backend
        
