name: Build

on:
  workflow_call:
    inputs:
      REGISTRY:
        required: true
        type: string
    secrets:
      GITLAB_LOGIN:
        required: true
      GITLAB_PASS:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: üîç Debug
        run: |
          ls -la
          [ -f Dockerfile ] && echo "‚úÖ Dockerfile OK" || (echo "‚ùå Missing"; exit 1)
        
      - name: Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ secrets.GITLAB_LOGIN }}
          password: ${{ secrets.GITLAB_PASS }}
            
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ inputs.REGISTRY }}/wmgcat.net/backend:latest